### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by AlexanderLanin** [eclipse-score/docs-as-code#18]
Currently releases involve some manual steps:
* Create tag in this repository
* Create release in this repository
* Create PR in bazel_registry repository
* Create PR in user repositories (will be handled by renovatebot in the future)
* Create a script/workflow that creates automatic PRs whenever there is a new tooling repository tag
* Create a way to introduce changelogs 

Can we automate/simplify any of this?

**Comment by Aymen-Soussi-01** [comment]
<p><strong>Proposal for Automating Python Project Releases</strong></p>

<p>Our current release process includes several manual steps:</p>
<ul>
  <li>Create a tag in this repository</li>
  <li>Create a release in this repository</li>
  <li>Create PRs in a central repository</li>
  <li>Create PRs in user repositories (to be automated later with RenovateBot)</li>
</ul>

<p>To simplify and automate these tasks, we can adopt a Python-native release tool. While GoReleaser is popular for Go projects, it is not designed for Python. Instead, here are suitable alternatives that align with Python project workflows and can automate many of the steps listed above:</p>

<h4>Recommended Tools</h4>

<ul>
  <li><strong>Hatch:</strong> Supports automated versioning, packaging, and publishing. Plugins allow scripting post-release actions, such as triggering PRs or tagging.</li>
  <li><strong>Poetry:</strong> Good for dependency and version management. Requires scripting or CI workflows for tagging and PR creation.</li>
  <li><strong>GitHub Actions + Twine:</strong> For a custom workflow, use GitHub Actions to create tags and releases, and Twine to publish to PyPI.</li>
  <li><strong>Release Drafter:</strong> GitHub app to auto-generate release notes and prepare releases based on merged PRs.</li>
  <li><strong>RenovateBot:</strong> Can automate PRs in dependent/user repositories once release versions are available.</li>
</ul>

<p>To fully automate your release workflow, consider the following best practices:</p>
<ul>
  <li>Use GitHub Actions to trigger a workflow when a tag is pushed.</li>
  <li>Automate changelog generation and release creation using tools like Release Drafter.</li>
  <li>Use Hatch or Poetry for consistent versioning and packaging.</li>
  <li>Use Twine within the CI to publish built distributions.</li>
  <li>Integrate RenovateBot to create follow-up PRs in downstream repositories.</li>
</ul>

<h4>Comparison Summary</h4>

<table>
  <thead>
    <tr>
      <th>Feature / Tool</th>
      <th>Poetry</th>
      <th>Hatch</th>
      <th>Twine</th>
      <th>GitHub Actions</th>
      <th>Release Drafter</th>
      <th>RenovateBot</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Tag creation</td>
      <td>No</td>
      <td>Optional via plugin</td>
      <td>No</td>
      <td>Yes</td>
      <td>Yes (draft only)</td>
      <td>No</td>
    </tr>
    <tr>
      <td>Release notes</td>
      <td>No</td>
      <td>No</td>
      <td>No</td>
      <td>Yes (with scripts)</td>
      <td>Yes</td>
      <td>No</td>
    </tr>
    <tr>
      <td>Push to PyPI</td>
      <td>Yes</td>
      <td>Yes</td>
      <td>Yes</td>
      <td>Yes (via Twine)</td>
      <td>No</td>
      <td>No</td>
    </tr>
    <tr>
      <td>Create PRs in core repo</td>
      <td>Manual</td>
      <td>Scriptable</td>
      <td>No</td>
      <td>Yes (with GitHub CLI)</td>
      <td>No</td>
      <td>No</td>
    </tr>
    <tr>
      <td>Create PRs in user repos</td>
      <td>No</td>
      <td>No</td>
      <td>No</td>
      <td>Optional via workflows</td>
      <td>No</td>
      <td>Yes</td>
    </tr>
  </tbody>
</table>

<p><strong>Conclusion:</strong> A combination of Hatch (for packaging/versioning), GitHub Actions (for automation), and Release Drafter + RenovateBot (

**Comment by Aymen-Soussi-01** [comment]
@MaximilianSoerenPollak  I updated the investigation on top to avoid the repetition

**Comment by AlexanderLanin** [comment]
Looking at the table I don’t understand the recommendation: Why should we use poetry or hatch if they don’t help us?

**Comment by Aymen-Soussi-01** [comment]
@AlexanderLanin I updated the investigation now, and I removed the unnecessary tools from the recommendation section as they do support PyPI, and also from the table of comparison.

**Comment by MaximilianSoerenPollak** [comment]
The question I think that is important to figure out here, you write about using 'custom scripts' for some of these jobs. 
How are we going to run them? 
How are we going to deploy / develop / test them? 
What exactly do they need to do (in this scenario), and what expertise do we need for this? 

Just to state it, what we would like the 'release part' to do is basically this: 
1. Create a new release with relevant Changelog 
2. Make a PR to 'bazel_registry' with new release (copy MODULE.bazel, add the version to metadata.json, and change source.json) 
 

And then the 'renovate bot' can check the latest registry entry and make a PR to bump the versions in the Repos if they use an older one.


I'm a bit skeptical that it will be 'minimal manual effort' to write all of those scripts etc. but I haven't looked into ti much so maybe possible.

**Comment by AlexanderLanin** [comment]
Maybe parts are possible via scripting gh-cli. Alternatively via github graphql lib.

**Comment by AlexanderLanin** [comment]
> We have also some kind of release cli tooling. I don't know how far you are currently: [mercedes-benz/gitflow-cli](https://github.com/mercedes-benz/gitflow-cli?rgh-link-date=2025-06-03T13%3A53%3A58.000Z)

At first glance, it seems focused on automating gitflow processes. That’s interesting, though in our case the challenges we’re facing are more on the Bazel side rather than with Git itself — especially since we follow a continuous integration approach in all of our infrastructure repositories.

**Comment by FScholPer** [comment]
Some vibe coding try  ;): 
```
name: Automate Bazel Registry Updates

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags

jobs:
  detect-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

  update-bazel-registry:
    needs: detect-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy updated MODULE.bazel
        run: cp path/to/MODULE.bazel path/to/bazel_registry/MODULE.bazel

      - name: Update metadata.json
        run: |
          VERSION=${{ env.VERSION }}
          jq --arg version "$VERSION" '.versions += [$version]' path/to/bazel_registry/metadata.json > tmp.json && mv tmp.json path/to/bazel_registry/metadata.json

      - name: Update source.json
        run: |
          VERSION=${{ env.VERSION }}
          jq --arg url "https://github.com/your_repo/releases/tag/$VERSION" '.source.url = $url' path/to/bazel_registry/source.json > tmp.json && mv tmp.json path/to/bazel_registry/source.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add path/to/bazel_registry/
          git commit -m "Update Bazel registry for version ${{ env.VERSION }}"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Bazel registry for version ${{ env.VERSION }}
          branch: update-bazel-registry-${{ env.VERSION }}
          title: Update Bazel registry for version ${{ env.VERSION }}
          body: Automated update of Bazel registry for version ${{ env.VERSION }}
          base: main

  validate-release:
    needs: update-bazel-registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate release
        run: |
          VERSION=${{ env.VERSION }}
          # Add your validation scripts here
          echo "Validating release $VERSION"
```
